### ISSUE TITLE
ไฟล์ XadesBesVerifyMain.java รันแล้ว error 

### ISSUE THREAD

**Issue by pikgoro** [ETDA/etax-xades#18]
ใน etax-xades.properties ไม่มี directory certStore ด้วยครับ

CERT_STORE_DIR=src/main/resources/certStore/

==============	Verify	==============
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.ReflectUtils$2 (file:/C:/Users/.m2/repository/com/google/inject/guice/2.0/guice-2.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
xades4j.providers.CannotBuildCertificationPathException: unable to find valid certification path to requested target
	at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:257)
	at xades4j.verification.XadesVerifierImpl.verify(XadesVerifierImpl.java:175)
	at XadesBesVerifier.verifyBes(XadesBesVerifier.java:106)
	at XadesBesVerifyMain.main(XadesBesVerifyMain.java:33)
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at xades4j.providers.impl.PKIXCertificateValidationProvider.validate(PKIXCertificateValidationProvider.java:253)
	... 3 more
==============	Finish	==============

**Comment by nathamETDA** [comment]
certStore folder is not available on git because it is an empty folder.
You can create an empty certStore folder to run the code.
I might add some a dummy certificate to make it not empty later.

**Comment by nathamETDA** [comment]
Close this issue due to inactivity in 30 days.
